// <auto-generated />
using System;
using AdmissionSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdmissionSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220913104635_tes")]
    partial class tes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdmissionSystem.Model.Accabtable_config", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Accepted_Or_Not")
                        .HasColumnType("bit");

                    b.Property<string>("Accepted_wish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_Statues_of_admission_eligibiltyId")
                        .HasColumnType("int");

                    b.Property<int>("FK_studentId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("FK_Statues_of_admission_eligibiltyId");

                    b.HasIndex("FK_studentId")
                        .IsUnique();

                    b.ToTable("Accabtable_config");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Admission_Eligibilty_Certificate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FK_Type_of_high_school_Cirtificateid")
                        .HasColumnType("int");

                    b.Property<int>("FK_studentId")
                        .HasColumnType("int");

                    b.Property<string>("Image_of_crtificat_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAnguge_of_the_addmintion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subscription_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("The_Rate")
                        .HasColumnType("real");

                    b.Property<string>("check_recipt_image_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city_of_high_school_cirtificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("course_number")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_of_high_school_cirtificate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("wish1ID")
                        .HasColumnType("int");

                    b.Property<int?>("wish2ID")
                        .HasColumnType("int");

                    b.Property<int?>("wish3ID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("FK_Type_of_high_school_Cirtificateid");

                    b.HasIndex("FK_studentId")
                        .IsUnique();

                    b.HasIndex("wish1ID");

                    b.HasIndex("wish2ID");

                    b.HasIndex("wish3ID");

                    b.ToTable("Admission_Eligibilty_Certificate");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Broken_Relationshib_Stat_Dep_Chair", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Chair_count")
                        .HasColumnType("int");

                    b.Property<int>("FK_statues_Of_Admission_EligibiltyId")
                        .HasColumnType("int");

                    b.Property<int>("Fk_departmentId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("FK_statues_Of_Admission_EligibiltyId");

                    b.HasIndex("Fk_departmentId");

                    b.ToTable("Broken_Relationshib_Stat_Dep_Chair");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("country_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            id = 1,
                            country_name = "سوريا"
                        },
                        new
                        {
                            id = 2,
                            country_name = "الإمارات"
                        },
                        new
                        {
                            id = 3,
                            country_name = "الكويت"
                        },
                        new
                        {
                            id = 4,
                            country_name = "السعودية"
                        });
                });

            modelBuilder.Entity("AdmissionSystem.Model.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_facultyId")
                        .HasColumnType("int");

                    b.Property<string>("specialization_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("FK_facultyId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            id = 1,
                            FK_facultyId = 1,
                            specialization_name = "الطب"
                        },
                        new
                        {
                            id = 2,
                            FK_facultyId = 1,
                            specialization_name = "طب الأسنان"
                        },
                        new
                        {
                            id = 3,
                            FK_facultyId = 1,
                            specialization_name = "الصيدلة"
                        },
                        new
                        {
                            id = 4,
                            FK_facultyId = 2,
                            specialization_name = "الهندسة المعمارية"
                        },
                        new
                        {
                            id = 5,
                            FK_facultyId = 2,
                            specialization_name = "الهندسة المدنية"
                        },
                        new
                        {
                            id = 6,
                            FK_facultyId = 3,
                            specialization_name = "هندسة تقانة المعلومات"
                        },
                        new
                        {
                            id = 7,
                            FK_facultyId = 3,
                            specialization_name = "هندسة الميكاترونيكس"
                        },
                        new
                        {
                            id = 8,
                            FK_facultyId = 4,
                            specialization_name = "إدارة"
                        },
                        new
                        {
                            id = 9,
                            FK_facultyId = 4,
                            specialization_name = "تمويل بنوك"
                        },
                        new
                        {
                            id = 10,
                            FK_facultyId = 5,
                            specialization_name = "التصميم الداخلي"
                        },
                        new
                        {
                            id = 11,
                            FK_facultyId = 5,
                            specialization_name = "التصميم الغرافيكي"
                        },
                        new
                        {
                            id = 12,
                            FK_facultyId = 6,
                            specialization_name = "الحقوق"
                        });
                });

            modelBuilder.Entity("AdmissionSystem.Model.Department_relation_Type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("FK_type_Of_High_School_CirtificateId")
                        .HasColumnType("int");

                    b.Property<double>("Minemum_of_Rate")
                        .HasColumnType("float");

                    b.Property<double>("Rate_of_chaire_count")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("FK_DepartmentId");

                    b.HasIndex("FK_type_Of_High_School_CirtificateId");

                    b.ToTable("Department_relation_Type");

                    b.HasData(
                        new
                        {
                            id = 1,
                            FK_DepartmentId = 1,
                            FK_type_Of_High_School_CirtificateId = 1,
                            Minemum_of_Rate = 83.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 2,
                            FK_DepartmentId = 2,
                            FK_type_Of_High_School_CirtificateId = 1,
                            Minemum_of_Rate = 78.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 3,
                            FK_DepartmentId = 3,
                            FK_type_Of_High_School_CirtificateId = 1,
                            Minemum_of_Rate = 78.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 4,
                            FK_DepartmentId = 4,
                            FK_type_Of_High_School_CirtificateId = 1,
                            Minemum_of_Rate = 68.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 5,
                            FK_DepartmentId = 5,
                            FK_type_Of_High_School_CirtificateId = 1,
                            Minemum_of_Rate = 68.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 6,
                            FK_DepartmentId = 6,
                            FK_type_Of_High_School_CirtificateId = 1,
                            Minemum_of_Rate = 68.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 7,
                            FK_DepartmentId = 6,
                            FK_type_Of_High_School_CirtificateId = 4,
                            Minemum_of_Rate = 83.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 8,
                            FK_DepartmentId = 7,
                            FK_type_Of_High_School_CirtificateId = 1,
                            Minemum_of_Rate = 68.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 9,
                            FK_DepartmentId = 7,
                            FK_type_Of_High_School_CirtificateId = 4,
                            Minemum_of_Rate = 83.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 10,
                            FK_DepartmentId = 8,
                            FK_type_Of_High_School_CirtificateId = 1,
                            Minemum_of_Rate = 56.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 11,
                            FK_DepartmentId = 8,
                            FK_type_Of_High_School_CirtificateId = 2,
                            Minemum_of_Rate = 56.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 12,
                            FK_DepartmentId = 8,
                            FK_type_Of_High_School_CirtificateId = 3,
                            Minemum_of_Rate = 63.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 13,
                            FK_DepartmentId = 9,
                            FK_type_Of_High_School_CirtificateId = 1,
                            Minemum_of_Rate = 56.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 14,
                            FK_DepartmentId = 9,
                            FK_type_Of_High_School_CirtificateId = 2,
                            Minemum_of_Rate = 56.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 15,
                            FK_DepartmentId = 9,
                            FK_type_Of_High_School_CirtificateId = 3,
                            Minemum_of_Rate = 63.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 16,
                            FK_DepartmentId = 10,
                            FK_type_Of_High_School_CirtificateId = 1,
                            Minemum_of_Rate = 56.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 17,
                            FK_DepartmentId = 10,
                            FK_type_Of_High_School_CirtificateId = 2,
                            Minemum_of_Rate = 56.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 18,
                            FK_DepartmentId = 10,
                            FK_type_Of_High_School_CirtificateId = 5,
                            Minemum_of_Rate = 63.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 19,
                            FK_DepartmentId = 11,
                            FK_type_Of_High_School_CirtificateId = 1,
                            Minemum_of_Rate = 56.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 20,
                            FK_DepartmentId = 11,
                            FK_type_Of_High_School_CirtificateId = 2,
                            Minemum_of_Rate = 56.0,
                            Rate_of_chaire_count = 0.0
                        },
                        new
                        {
                            id = 21,
                            FK_DepartmentId = 11,
                            FK_type_Of_High_School_CirtificateId = 5,
                            Minemum_of_Rate = 63.0,
                            Rate_of_chaire_count = 0.0
                        });
                });

            modelBuilder.Entity("AdmissionSystem.Model.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nick_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone_Number")
                        .HasColumnType("int");

                    b.Property<int>("The_ID_Number")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Birth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "useer2@localhost",
                            Gender = "Male",
                            Nick_Name = "adm",
                            Phone_Number = 987,
                            The_ID_Number = 8765,
                            Type = "Admin",
                            name = "Admin1"
                        },
                        new
                        {
                            id = 2,
                            Birth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "useer2@localhost",
                            Gender = "Male",
                            Nick_Name = "adm",
                            Phone_Number = 987,
                            The_ID_Number = 8765,
                            Type = "Admin",
                            name = "Admin2"
                        });
                });

            modelBuilder.Entity("AdmissionSystem.Model.Faculty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Faculty_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Faculty");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Faculty_name = "كلية طبية"
                        },
                        new
                        {
                            id = 2,
                            Faculty_name = "كلية الهندسة المدنية والمعمارية"
                        },
                        new
                        {
                            id = 3,
                            Faculty_name = "كلية الهندسة"
                        },
                        new
                        {
                            id = 4,
                            Faculty_name = "كليةالأعمال والإدارة"
                        },
                        new
                        {
                            id = 5,
                            Faculty_name = "كليةالفنون والإعلام"
                        },
                        new
                        {
                            id = 6,
                            Faculty_name = "كليةالحقوق والعلوم الإنسانية"
                        });
                });

            modelBuilder.Entity("AdmissionSystem.Model.Identity_classes.MyIdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Identity_classes.MyIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TheIDnumber")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Persentage_count_for_each__country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_countryId")
                        .HasColumnType("int");

                    b.Property<int>("FK_statues_of_admission_eligibiltyId")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("FK_countryId");

                    b.HasIndex("FK_statues_of_admission_eligibiltyId");

                    b.ToTable("Persentage_count_for_each__country");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Statues_Of_Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Checked_Identity")
                        .HasColumnType("bit");

                    b.Property<bool>("Checked_Rate")
                        .HasColumnType("bit");

                    b.Property<bool>("Checked_city_certificate")
                        .HasColumnType("bit");

                    b.Property<bool>("Checked_recipet")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date_of_Acshiving")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FK_Employee_Infoid")
                        .HasColumnType("int");

                    b.Property<int>("FK_Student_InfoId")
                        .HasColumnType("int");

                    b.Property<bool>("loack")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("FK_Employee_Infoid");

                    b.HasIndex("FK_Student_InfoId")
                        .IsUnique();

                    b.ToTable("Statues_Of_Student");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Statues_of_admission_eligibilty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Begaining_date_of_the_process")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number_Student")
                        .HasColumnType("int");

                    b.Property<string>("Type_of_admission_eligibilty")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<DateTime>("semester_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("semester_no")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Statues_of_admission_eligibilty");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Cirtificate_cityid")
                        .HasColumnType("int");

                    b.Property<string>("Civil_Registriation_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Civil_Registrition_No")
                        .HasColumnType("int");

                    b.Property<int>("Conformation")
                        .HasColumnType("int");

                    b.Property<string>("Current_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Father_Name_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Father_Name_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fk_Cirtificate_cityId")
                        .HasColumnType("int");

                    b.Property<string>("Full_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grandfather_Name_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grandfather_Name_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_s_Phone")
                        .HasColumnType("int");

                    b.Property<int>("Identity_No")
                        .HasColumnType("int");

                    b.Property<string>("Identity_back_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity_front_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marital_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mobile_Phone")
                        .HasColumnType("int");

                    b.Property<string>("Mother_Name_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_Name_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nick_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Passport_No")
                        .HasColumnType("int");

                    b.Property<int?>("Statues_Of_Admission_Eligibiltyid")
                        .HasColumnType("int");

                    b.Property<double?>("UnvirstyId")
                        .HasColumnType("float");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("high_school_certificate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Cirtificate_cityid");

                    b.HasIndex("Statues_Of_Admission_Eligibiltyid");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Tracking_Rate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Of_Modification")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FK_Employee_Infoid")
                        .HasColumnType("int");

                    b.Property<int>("FK_Student_InfoId")
                        .HasColumnType("int");

                    b.Property<string>("new_country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("new_rate")
                        .HasColumnType("real");

                    b.Property<string>("new_typeofcertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("old_country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("old_rate")
                        .HasColumnType("real");

                    b.Property<string>("old_typeofcertificate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("FK_Employee_Infoid");

                    b.HasIndex("FK_Student_InfoId")
                        .IsUnique();

                    b.ToTable("Tracking_Rate");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Type_of_high_school_Cirtificate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("id");

                    b.ToTable("Type_of_high_school_Cirtificate");

                    b.HasData(
                        new
                        {
                            id = 1,
                            type = "علمي"
                        },
                        new
                        {
                            id = 2,
                            type = "أدبي"
                        },
                        new
                        {
                            id = 3,
                            type = "تجارة"
                        },
                        new
                        {
                            id = 4,
                            type = "مهني حاسوب"
                        },
                        new
                        {
                            id = 5,
                            type = "مهني فنون"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Accabtable_config", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Statues_of_admission_eligibilty", "FK_Statues_of_admission_eligibilty")
                        .WithMany()
                        .HasForeignKey("FK_Statues_of_admission_eligibiltyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdmissionSystem.Model.Student", "FK_student")
                        .WithOne("FK_Accabtable_configInfo")
                        .HasForeignKey("AdmissionSystem.Model.Accabtable_config", "FK_studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmissionSystem.Model.Admission_Eligibilty_Certificate", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Type_of_high_school_Cirtificate", "FK_Type_of_high_school_Cirtificate")
                        .WithMany()
                        .HasForeignKey("FK_Type_of_high_school_Cirtificateid");

                    b.HasOne("AdmissionSystem.Model.Student", "FK_student")
                        .WithOne("FK_Admission_Eligibilty_Requist_For_UNsy_Certificate")
                        .HasForeignKey("AdmissionSystem.Model.Admission_Eligibilty_Certificate", "FK_studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdmissionSystem.Model.Department_relation_Type", "wish1")
                        .WithMany()
                        .HasForeignKey("wish1ID");

                    b.HasOne("AdmissionSystem.Model.Department_relation_Type", "wish2")
                        .WithMany()
                        .HasForeignKey("wish2ID");

                    b.HasOne("AdmissionSystem.Model.Department_relation_Type", "wish3")
                        .WithMany()
                        .HasForeignKey("wish3ID");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Broken_Relationshib_Stat_Dep_Chair", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Statues_of_admission_eligibilty", "FK_statues_Of_Admission_Eligibilty")
                        .WithMany()
                        .HasForeignKey("FK_statues_Of_Admission_EligibiltyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdmissionSystem.Model.Department", "Fk_department")
                        .WithMany()
                        .HasForeignKey("Fk_departmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmissionSystem.Model.Department", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Faculty", "FK_faculty")
                        .WithMany()
                        .HasForeignKey("FK_facultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmissionSystem.Model.Department_relation_Type", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Department", "FK_Department")
                        .WithMany()
                        .HasForeignKey("FK_DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdmissionSystem.Model.Type_of_high_school_Cirtificate", "FK_type_Of_High_School_Cirtificate")
                        .WithMany()
                        .HasForeignKey("FK_type_Of_High_School_CirtificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmissionSystem.Model.Persentage_count_for_each__country", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Country", "FK_country")
                        .WithMany()
                        .HasForeignKey("FK_countryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdmissionSystem.Model.Statues_of_admission_eligibilty", "FK_statues_of_admission_eligibilty")
                        .WithMany()
                        .HasForeignKey("FK_statues_of_admission_eligibiltyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmissionSystem.Model.Statues_Of_Student", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Employee", "FK_Employee_Info")
                        .WithMany()
                        .HasForeignKey("FK_Employee_Infoid");

                    b.HasOne("AdmissionSystem.Model.Student", "FK_Student_Info")
                        .WithOne("Statues_Of_Student")
                        .HasForeignKey("AdmissionSystem.Model.Statues_Of_Student", "FK_Student_InfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmissionSystem.Model.Student", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Country", "Cirtificate_city")
                        .WithMany()
                        .HasForeignKey("Cirtificate_cityid");

                    b.HasOne("AdmissionSystem.Model.Statues_of_admission_eligibilty", "Statues_Of_Admission_Eligibilty")
                        .WithMany()
                        .HasForeignKey("Statues_Of_Admission_Eligibiltyid");
                });

            modelBuilder.Entity("AdmissionSystem.Model.Tracking_Rate", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Employee", "FK_Employee_Info")
                        .WithMany()
                        .HasForeignKey("FK_Employee_Infoid");

                    b.HasOne("AdmissionSystem.Model.Student", "FK_Student_Info")
                        .WithOne("Tracking_Rate")
                        .HasForeignKey("AdmissionSystem.Model.Tracking_Rate", "FK_Student_InfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Identity_classes.MyIdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Identity_classes.MyIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Identity_classes.MyIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Identity_classes.MyIdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdmissionSystem.Model.Identity_classes.MyIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AdmissionSystem.Model.Identity_classes.MyIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
